name = "ronnieragusa-executivesearch-calculator"
main = "./worker.ts"
compatibility_date = "2026-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "allsearch-executive-compensation"
database_id = "21dfb044-5261-46c7-818a-42d10fd79c40"

[assets]
directory = "./dist/public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]